install:
  - sudo apt-get update
  - wget https://hackage.haskell.org/package/pandoc-2.2.3.2/pandoc-2.2.3.2.tar.gz
  - wget -qO- https://get.haskellstack.org/ | sh
  - tar xvzf pandoc-2.2.3.2.tar.gz
  - cd pandoc-2.2.3.2
  - stack setup
  - stack install

env:
  - PATH=$PATH:~/.local/bin

script:
  - pwd
  - cd ~/cloudmesh-community/book/big-data-applications
  - pandoc --version
  - make
  - cd ~/cloudmesh-community/book/cloud
  - pandoc --version
  - make