version: 2
jobs:
  build:
    docker:
      - image: cloudmesh/book:1.0
    steps:
      - checkout
      - run:
          name: where
          command: ls; pwd
      - run:
          name: which python3
          command: which python3
      - run:
          name: install python3
          command: update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
      - run:
          name: config python3
          command: update-alternatives --config python
      - run:
          name: python version
          command: python --version
      - run:
          name: pip version
          command: pip --version
      - run:
          name: pandoc version
          command: pandoc --version
      - run:
          name: git pull
          command: git pull
      - run:
          name: requirements.txt
          command: pip install -r requirements.txt
      - run:
          name: manifest-parser
          command: ../bin/manifest-parser.py dep BOOK_516
      - run:
          name: check cloud
          command: cd cloud && make new && cd ..
      - run:
          name: check cloud
          command: cd big-data-applications && make
