version: 2
jobs:
  build:
    docker:
      - image: cloudmesh/technologies:1.3
    steps:
      - checkout
      - run:
          name: where
          command: ls; pwd
      - run:
          name: which python3
          command: which python3
      - run:
          name: python version
          command: python --version
      - run:
          name: pandoc version
          command: pandoc --version
      - run:
          name: requirements.txt
          command: pip install -r requirements.txt
      - run:
          name: check cloud
          command: cd cloud && make new 
      - run:
          name: check cloud 
          command: cd big-data-applications && make

