version: 2
jobs:
  build:
    docker:
      - image: cloudmesh/book:1.0
    steps:
      - checkout
      - run:
          name: where
          command: ls; pwd
      - run:
          name: which python
          command: which python
      - run:
          name: python version
          command: python --version
      - run:
          name: pip version
          command: pip --version
      - run:
          name: pandoc version
          command: pandoc --version
      - run:
          name: requirements.txt
          command: pip install -r requirements.txt
      - run:
          name: changed files
          command: git diff-tree --no-commit-id --name-only -r HEAD > changed_files.log && cat changed_files.log
      - run:
          name: check cloud
          command: cd cloud && make new && cd ..
      - run:
          name: check cloud
          command: cd big-data-applications && make
      - store_artifacts:
          path: dest/references.bib
          destination: references.bib
