version: 2
jobs:
  build:
    docker:
      - image: cloudmesh/book:1.0
    steps:
      - checkout
      - run:
          name: where
          command: ls; pwd
      - run:
          name: which python
          command: which python
      - run:
          name: python version
          command: python --version
      - run:
          name: pip version
          command: pip --version
      - run:
          name: pandoc version
          command: pandoc --version
      - run:
          name: requirements.txt
          command: pip install -r requirements.txt
      - run:
          name: changed files
          command: git diff-tree --no-commit-id --name-only -r HEAD > changed_files.log && cat changed_files.log
      - run:
          name: biber
          command: bin/check-biber.sh changed_files.log
      - run:
          name: bibtex issues
          command: cd cloud; make bibtex-issues
      - run:
          name: check cloud epub
          command: cd cloud && make new && cd ..
      - run:
          name: check bigdata epub
          command: cd big-data-applications && make
      - run:
          name: add line numbers to references.bib
          command: cat -n big-data-applications/dest/references.bib > references.bib
      - store_artifacts:
          path: references.bib
          destination: references.bib
